spring.application.name=adventure-log-backend

spring.datasource.url=jdbc:mysql://localhost:3306/adventure_log
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# TODO: set to false before deploying to production
spring.jpa.show-sql=true